import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Button } from '@chakra-ui/react'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>庫庫資訊</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Button colorScheme="blue">Button</Button>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}
