// const defaultlayout = (
//   <div className={styles.container}>
//     <Head>
//       <title>庫庫資訊</title>
//       <meta name="description" content="Generated by create next app" />
//       <link rel="icon" href="/favicon.ico" />
//     </Head>
//     <Header />
//     <main className={styles.main}>
//       <Button colorScheme="blue">Button</Button>
//     </main>

//     <footer className={styles.footer}></footer>
//   </div>
// )
